[program:consulting-backend-fastapi]
command=/home/ubuntu/.local/bin/uvicorn main:app --workers 4 --host 127.0.0.1 --port 8000
directory=/home/ubuntu/dev/consulting-backend-fastapi/backend/core
user=ubuntu
autorestart=true
redirect_stderr=true
stdout_logfile = /home/ubuntu/dev/consulting-backend-fastapi/logs/debug.log