from __future__ import annotations

from typing import TypeVar

from sqlalchemy.sql.selectable import Select
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, Session, scoped_session

from sqlalchemy.exc import ProgrammingError, DatabaseError, NoResultFound, OperationalError, IntegrityError

TModelType = TypeVar("TModelType")
TQueryType = TypeVar("TQueryType")


class DBClient:
    _ERROR_MSG_TEMPLATE: str = 'Failed to {operation} obj. Error: {e}'
    _UNEXPECTED_ERROR_MSG_TEMPLATE: str = 'Unexpected error. Failed to {operation} object. Error: {e}'

    def __init__(self, uri: str) -> None:
        self._engine = create_engine(uri)
        self._async_session: sessionmaker[Session] | None = None

    def _get_session(self):
        if not self._async_session:
            self._async_session = scoped_session(
                sessionmaker(bind=self._engine, expire_on_commit=False)
            )
        return self._async_session
    
    def select_number_of_rows_by_query(self, query: Select) -> TModelType | None:
        session = self._get_session()
        try:
            result = session().execute(query).scalar()  # Call the `session()` to get the actual session object
            return result
        except Exception as e:
            print(f"Error executing query: {e}")
            raise
        # finally:
        #     session.remove()

    def select_one_object_by_query(self, query: Select) -> TModelType | None:
        sync_session = self._get_session()
        try:
            with sync_session() as session:
                result = session.execute(query).unique()
                row = result.fetchone()
                if row:
                    # response = {"id": row[0].id, "ticker": row[0].ticker, "fullName": row[0].fullName}
                    # return response
                    return row

        except (ProgrammingError, DatabaseError) as e:
            error_msg = self._ERROR_MSG_TEMPLATE.format(operation='SELECT', e=e)
            raise OperationalError(e, error_msg) from e

        except Exception as e:
            error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='SELECT', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        try:
            coin = result.scalars().one()
        except NoResultFound:
            return None

        return coin

    def select_all_objects(self, query: Select) -> TModelType | None:
        sync_session = self._get_session()
        try:
            with sync_session() as session:
                result = session.execute(query).unique()
                rows = result.fetchall()
                objects = []
                if rows:
                    for row in rows:
                        obj = row[0]
                        objects.append(obj)
                return objects

        except (ProgrammingError, DatabaseError) as e:
            error_msg = self._ERROR_MSG_TEMPLATE.format(operation='SELECT', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        except Exception as e:
            error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='SELECT', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        try:
            coin = result.scalars().one()
        except NoResultFound:
            return None

        return coin

    def create_object(self, obj: TModelType) -> TModelType | None:
        sync_session = self._get_session()
        try:
            with sync_session() as session:
                with session.begin():
                    session.add(obj)
                    # Flush and refresh so autogenerated fields like UUIDs are available.
                    session.flush()
                    session.refresh(obj)
        except (ProgrammingError, DatabaseError, IntegrityError) as e:
            error_msg = self._ERROR_MSG_TEMPLATE.format(operation='CREATE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e
        except Exception as e:
            error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='CREATE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        return obj

    def update_object(self, query: TQueryType) -> TModelType | None:
        sync_session = self._get_session()
        try:
            with sync_session() as session:
                # print("Query: ", query)
                result = session.execute(query)
                session.commit()
                print("Result: ", result)
                # row = result.fetchone()
                return "Object updated"

        except (ProgrammingError, DatabaseError) as e:
            error_msg = self._ERROR_MSG_TEMPLATE.format(operation='UPDATE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        except Exception as e:
            error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='UPDATE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

        try:
            coin = result.scalars().one()
        except NoResultFound:
            return None

        return coin
    
    # def update_one_field(self, query: TQueryType):
    #     sync_session = self._get_session()
    #     try:
    #         with sync_session() as session:
    #             # print("Query: ", query)
    #             result = session.execute(query)
    #             session.commit()
    #             # print(result)
    #             row = result.fetchone()
    #             # print("ROW:", row)
    #             return row[0]

    #     except (ProgrammingError, DatabaseError) as e:
    #         error_msg = self._ERROR_MSG_TEMPLATE.format(operation='UPDATE', e=e)
    #         raise OperationalError(e, error_msg, orig=BaseException()) from e

    #     except Exception as e:
    #         error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='UPDATE', e=e)
    #         raise OperationalError(e, error_msg, orig=BaseException()) from e

    def delete_object(self, obj: TModelType) -> TModelType | None:
        sync_session = self._get_session()
        # print("Object: ", obj)
        try:
            with sync_session() as session:
                with session.begin():
                    session.delete(obj)
                    return obj
        except (ProgrammingError, DatabaseError, IntegrityError) as e:
            error_msg = self._ERROR_MSG_TEMPLATE.format(operation='DELETE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e
        except Exception as e:
            error_msg = self._UNEXPECTED_ERROR_MSG_TEMPLATE.format(operation='DELETE', e=e)
            raise OperationalError(e, error_msg, orig=BaseException()) from e

    
