import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Providers } from "./providers";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Advicerr - платформа для консультацій",
  // description: "Generated by create next app",
  description: "Ми представляємо платформу для консультацій, щоб ви могли отримати доступ до знань інших спеціалістів.",
  robots: "index, follow",
  //viewport is set automatically.
  //charset is set automatically.
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html suppressHydrationWarning lang="en">
        <body className={inter.className}>
          <Providers>
            {children}
          </Providers>
        </body>
      </html>
  );
}
