"""Made tag names unique

Revision ID: 56e732200c88
Revises: fbd5fb80e821
Create Date: 2025-01-22 11:40:15.867640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e732200c88'
down_revision = 'fbd5fb80e821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rrn', sa.String(length=255), nullable=True),
    sa.Column('masked_card', sa.String(length=255), nullable=True),
    sa.Column('sender_cell_phone', sa.String(length=255), nullable=True),
    sa.Column('response_signature_string', sa.String(length=255), nullable=True),
    sa.Column('response_status', sa.String(length=255), nullable=True),
    sa.Column('sender_account', sa.String(length=255), nullable=True),
    sa.Column('fee', sa.String(length=255), nullable=True),
    sa.Column('rectoken_lifetime', sa.String(length=255), nullable=True),
    sa.Column('reversal_amount', sa.String(length=255), nullable=True),
    sa.Column('settlement_amount', sa.String(length=255), nullable=True),
    sa.Column('actual_amount', sa.String(length=255), nullable=True),
    sa.Column('order_status', sa.String(length=255), nullable=True),
    sa.Column('response_description', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=255), nullable=True),
    sa.Column('order_time', sa.String(length=255), nullable=True),
    sa.Column('actual_currency', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=True),
    sa.Column('parent_order_id', sa.String(length=255), nullable=True),
    sa.Column('merchant_data', sa.String(length=255), nullable=True),
    sa.Column('tran_type', sa.String(length=255), nullable=True),
    sa.Column('eci', sa.String(length=255), nullable=True),
    sa.Column('settlement_date', sa.String(length=255), nullable=True),
    sa.Column('payment_system', sa.String(length=255), nullable=True),
    sa.Column('rectoken', sa.String(length=255), nullable=True),
    sa.Column('approval_code', sa.String(length=255), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('settlement_currency', sa.String(length=255), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=255), nullable=True),
    sa.Column('card_bin', sa.Integer(), nullable=True),
    sa.Column('response_code', sa.String(length=255), nullable=True),
    sa.Column('card_type', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_card_payment_id'), 'card_payment', ['id'], unique=False)
    op.create_unique_constraint(None, 'tags', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_index(op.f('ix_card_payment_id'), table_name='card_payment')
    op.drop_table('card_payment')
    # ### end Alembic commands ###
