"""Added rating

Revision ID: 9936a6ff0083
Revises: 56e732200c88
Create Date: 2025-01-24 12:32:52.620938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9936a6ff0083'
down_revision = '56e732200c88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
