"""Added cascades

Revision ID: e8c7adf69e71
Revises: 23a3eb05ca2a
Create Date: 2025-01-13 15:06:23.618597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c7adf69e71'
down_revision = '23a3eb05ca2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_client_id_fkey', 'order', type_='foreignkey')
    op.drop_constraint('order_consultant_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order', 'users', ['consultant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('review_consultant_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint('review_client_id_fkey', 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'users', ['consultant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review', 'users', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key('review_client_id_fkey', 'review', 'users', ['client_id'], ['id'])
    op.create_foreign_key('review_consultant_id_fkey', 'review', 'users', ['consultant_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_consultant_id_fkey', 'order', 'users', ['consultant_id'], ['id'])
    op.create_foreign_key('order_client_id_fkey', 'order', 'users', ['client_id'], ['id'])
    # ### end Alembic commands ###
