"""Added cascades

Revision ID: fbd5fb80e821
Revises: e8c7adf69e71
Create Date: 2025-01-13 15:07:32.274271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd5fb80e821'
down_revision = 'e8c7adf69e71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tags_users_user_id_fkey', 'tags_users', type_='foreignkey')
    op.drop_constraint('tags_users_tag_id_fkey', 'tags_users', type_='foreignkey')
    op.create_foreign_key(None, 'tags_users', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_users', type_='foreignkey')
    op.drop_constraint(None, 'tags_users', type_='foreignkey')
    op.create_foreign_key('tags_users_tag_id_fkey', 'tags_users', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('tags_users_user_id_fkey', 'tags_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
