version: "3.9"
services:
  api:
    build: ./backend
    command: bash -c "cd ./core/database && ls && alembic upgrade head && cd .. && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes: 
      - backend_api:/backend/core:ro
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - custom
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "1.0"
    #      memory: "512M"

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./backend/.env
    networks:
      - custom
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "1.0"
    #      memory: "1G"

  redis:
    image: redis:latest
    restart: always
    ports: 
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/root/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    networks:
      - custom
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.5"
    #      memory: "256M"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - custom
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.5"
    #      memory: "256M"

  next_app:
    container_name: next-app
    env_file:
      - ./advicerr-frontend/.env
    build:
      context: ./advicerr-frontend
      dockerfile: prod.Dockerfile
      args:
        # ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_URL_TO_API: https://advicerr.com/api/
    restart: always
    ports:
      - "3000:3000"
    networks:
      - custom
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "1.0"
    #      memory: "512M"
 
volumes:
  postgres_data:
  backend_api:
  redis_data:
  redis_config:

networks:
  custom:
    driver: bridge
    internal: true
