version: "3.9"
services:
  api:
    build: .
    command: bash -c "cd ./core/database && ls && alembic upgrade head && cd .. && uvicorn main:app --host 0.0.0.0"
    ports:
      - "8000:8000"
    volumes: 
      - backend_api:/backend/core
    env_file:
      - .env
    depends_on:
      - db 
      - redis
    networks:
      - custom

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=consultingdb
    networks:
      - custom

  redis:
    image: redis:latest
    restart: always
    ports: 
      - "6379:6379"
    volumes:
      - redis_data:/root/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    networks:
      - custom
 
volumes:
  postgres_data:
  backend_api:
  redis_data:
  redis_config:

networks:
  custom:
    driver: bridge