import React from 'react';
import Head from "next/head";
import {Header} from "../Header/Header";
import {Footer} from "../Footer/Footer";

type Props = {
    children: JSX.Element
}

const MainContainer: React.FC<Props> = ({children}: Props) => {
    return (
        <>
            <Head>
                {/* <title>Advicerr</title>
                <meta name="description" content="Generated by create next app" /> */}
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/*{BOXICONS}*/}
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"/>
                {/*Bootstrap*/}
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossOrigin="anonymous"></link>

                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
                <main className={`container-lg max-w-screen-xl px-4 sm:px-6 lg:px-8 mx-auto`} style={{minHeight: "90vh"}}>
                    {children}
                </main>
            <Footer/>
        </>
    );
};

export default MainContainer;