# renew_before_expiry = 30 days
version = 2.7.4
archive_dir = /etc/letsencrypt/archive/api.poradnyky.shop
cert = /etc/letsencrypt/live/api.poradnyky.shop/cert.pem
privkey = /etc/letsencrypt/live/api.poradnyky.shop/privkey.pem
chain = /etc/letsencrypt/live/api.poradnyky.shop/chain.pem
fullchain = /etc/letsencrypt/live/api.poradnyky.shop/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 4b485d293d898539558bdf48dd78851a
server = https://acme-staging-v02.api.letsencrypt.org/directory
authenticator = webroot
webroot_path = /var/www/certbot,
key_type = ecdsa
[[webroot_map]]
api.poradnyky.shop = /var/www/certbot
